using UnityEngine;
using UnityEngine.UI;
using TMPro;
using System.Text;
using System.Collections.Generic;

public class MedicalReportFormatter : MonoBehaviour
{
    [Header("Text Components")]
    public TextMeshProUGUI reportText;

    [Header("Medical Report Styling")]
    [SerializeField] private TMP_FontAsset headerFont;
    [SerializeField] private TMP_FontAsset bodyFont;
    [SerializeField] private float headerSize = 24f;
    [SerializeField] private float subHeaderSize = 18f;
    [SerializeField] private float bodySize = 14f;
    [SerializeField] private float lineSpacing = 1.2f;

    [Header("Colors")]
    public Color headerColor = new Color(0.2f, 0.4f, 0.6f, 1f);     // 医疗蓝
    public Color subHeaderColor = new Color(0.3f, 0.3f, 0.3f, 1f);  // 深灰
    public Color bodyColor = new Color(0.2f, 0.2f, 0.2f, 1f);       // 文本黑
    public Color scoreColor = new Color(0.8f, 0.4f, 0.2f, 1f);      // 分数橙
    public Color passColor = new Color(0.2f, 0.6f, 0.2f, 1f);       // 通过绿
    public Color failColor = new Color(0.8f, 0.2f, 0.2f, 1f);       // 未通过红

    void Start()
    {
        if (reportText == null)
            reportText = GetComponent<TextMeshProUGUI>();

        SetupTextProperties();
    }

    private void SetupTextProperties()
    {
        if (reportText != null)
        {
            reportText.fontSize = bodySize;
            reportText.lineSpacing = lineSpacing;
            reportText.color = bodyColor;
            reportText.alignment = TextAlignmentOptions.TopLeft;
            reportText.enableWordWrapping = true;
            reportText.overflowMode = TextOverflowModes.Overflow;
        }
    }

    public string FormatMedicalReport(DynamicEvaluationResult evaluation, int conversationCount)
    {
        StringBuilder formattedReport = new StringBuilder();

        // 报告头部
        formattedReport.Append(CreateHeader());
        formattedReport.AppendLine();

        // 基本信息
        formattedReport.Append(CreateBasicInfo(conversationCount));
        formattedReport.AppendLine();

        // 评估标准详情
        formattedReport.Append(CreateAssessmentDetails(evaluation.criteria));
        formattedReport.AppendLine();

        // 总结评估
        formattedReport.Append(CreateOverallAssessment(evaluation));
        formattedReport.AppendLine();

        // 总结和建议
        formattedReport.Append(CreateSummaryAndRecommendations(evaluation));

        return formattedReport.ToString();
    }

    private string CreateHeader()
    {
        StringBuilder header = new StringBuilder();

        header.AppendLine($"<size={headerSize}><color=#{ColorUtility.ToHtmlStringRGB(headerColor)}><b>AI INTERACTION FEEDBACK REPORT</b></color></size>");
        header.AppendLine($"<color=#{ColorUtility.ToHtmlStringRGB(subHeaderColor)}>Transcript-Based Interaction Review</color>");
        header.AppendLine("=================================================");
        header.AppendLine();

        // 报告信息
        header.AppendLine($"<b>Date:</b> {System.DateTime.Now:MMMM dd, yyyy}");
        header.AppendLine($"<b>Time:</b> {System.DateTime.Now:HH:mm}");
        header.AppendLine($"<b>Feedback Type:</b> Supplementary AI Interaction Feedback");
        header.AppendLine($"<b>Generated By:</b> AI Feedback System");

        return header.ToString();
    }

    private string CreateBasicInfo(int conversationCount)
    {
        StringBuilder info = new StringBuilder();

        info.AppendLine($"<size={subHeaderSize}><color=#{ColorUtility.ToHtmlStringRGB(subHeaderColor)}><b>INTERACTION SUMMARY</b></color></size>");
        info.AppendLine("=========================================");
        info.AppendLine();
        info.AppendLine($"• <b>Total Dialogue Exchanges:</b> {conversationCount}");
        info.AppendLine($"• <b>Session Duration:</b> Complete interaction recorded");
        info.AppendLine($"• <b>Review Basis:</b> Student-patient transcript and interaction flow");
        info.AppendLine($"• <b>Feedback Focus:</b> Cueing behavior, response opportunities, and supportive communication");

        return info.ToString();
    }

    private string CreateAssessmentDetails(List<CriterionScore> criteria)
    {
        StringBuilder details = new StringBuilder();

        details.AppendLine($"<size={subHeaderSize}><color=#{ColorUtility.ToHtmlStringRGB(subHeaderColor)}><b>INTERACTION FEEDBACK DETAILS</b></color></size>");
        details.AppendLine("=========================================");
        details.AppendLine();

        for (int i = 0; i < criteria.Count; i++)
        {
            var criterion = criteria[i];

            details.AppendLine($"<b>{i + 1}. {criterion.name.ToUpper()}</b>");
            details.AppendLine($"   <i>Feedback:</i> {criterion.explanation}");
            details.AppendLine();
        }

        return details.ToString();
    }

    private string CreateOverallAssessment(DynamicEvaluationResult evaluation)
    {
        StringBuilder assessment = new StringBuilder();

        assessment.AppendLine($"<size={subHeaderSize}><color=#{ColorUtility.ToHtmlStringRGB(subHeaderColor)}><b>OVERALL INTERACTION FEEDBACK</b></color></size>");
        assessment.AppendLine("=========================================");
        assessment.AppendLine();
        assessment.AppendLine($"<b>Summary:</b>");
        assessment.AppendLine($"{evaluation.overallExplanation}");

        return assessment.ToString();
    }

    private string CreateSummaryAndRecommendations(DynamicEvaluationResult evaluation)
    {
        StringBuilder summary = new StringBuilder();

        summary.AppendLine($"<size={subHeaderSize}><color=#{ColorUtility.ToHtmlStringRGB(subHeaderColor)}><b>LEARNING RECOMMENDATIONS</b></color></size>");
        summary.AppendLine("=========================================");
        summary.AppendLine();

        // 基于分数提供建议
        List<string> recommendations = GenerateRecommendations(evaluation.criteria);

        foreach (var recommendation in recommendations)
        {
            summary.AppendLine($"• {recommendation}");
        }

        summary.AppendLine();
        summary.AppendLine("=========================================");
        summary.AppendLine($"<i>Report generated on {System.DateTime.Now:MMMM dd, yyyy} at {System.DateTime.Now:HH:mm}</i>");
        summary.AppendLine($"<i>For questions about this assessment, consult with your clinical instructor.</i>");

        return summary.ToString();
    }

    private List<string> GenerateRecommendations(List<CriterionScore> criteria)
    {
        List<string> recommendations = new List<string>();

        foreach (var criterion in criteria)
        {
            float percentage = (float)criterion.score / criterion.maxScore;

            if (percentage < 0.5f)
            {
                switch (criterion.name.ToLower())
                {
                    case var name when name.Contains("rapport"):
                        recommendations.Add("Focus on building stronger therapeutic relationships through active listening and empathy");
                        break;
                    case var name when name.Contains("communication"):
                        recommendations.Add("Practice clear, professional communication techniques and active listening skills");
                        break;
                    case var name when name.Contains("information"):
                        recommendations.Add("Develop systematic approaches to gathering comprehensive patient information");
                        break;
                    case var name when name.Contains("clinical"):
                        recommendations.Add("Strengthen clinical reasoning skills through case study practice");
                        break;
                    case var name when name.Contains("professional"):
                        recommendations.Add("Review professional nursing standards and practice professional communication");
                        break;
                    default:
                        recommendations.Add($"Continue developing skills in {criterion.name.ToLower()}");
                        break;
                }
            }
        }

        if (recommendations.Count == 0)
        {
            recommendations.Add("Continue practicing excellent communication skills in various clinical scenarios");
            recommendations.Add("Consider mentoring junior nursing students to reinforce your strong skills");
        }

        return recommendations;
    }

    // 公共方法：应用格式化后的报告
    public void ApplyFormattedReport(DynamicEvaluationResult evaluation, int conversationCount)
    {
        if (reportText == null)
            return;

        if (HasNarrativeSections(evaluation))
        {
            reportText.text = FormatSharedNarrativeReport(evaluation, conversationCount);
            return;
        }

        string formattedContent = FormatMedicalReport(evaluation, conversationCount);
        reportText.text = formattedContent;
    }

    // =====================================================================
    // Shared narrative feedback render branch (Phase 1 AI Interaction,
    // Phase 2 Training, future Phase 3 AI / Faculty).
    // =====================================================================

    private static readonly string[] CanonicalSectionOrder =
    {
        "overall_summary",
        "interaction_overview",
        "rapport_communication",
        "clinical_reasoning",
        "professionalism",
        "assessment_judgment",
        "cueing_strategy",
        "prompting_quality",
        "adaptation_to_patient",
        "supportive_communication",
        "strengths",
        "priority_improvements",
        "next_step_practice"
    };

    private static bool HasNarrativeSections(DynamicEvaluationResult evaluation)
    {
        if (evaluation == null || evaluation.feedbackSections == null)
            return false;

        foreach (NarrativeFeedbackSection section in evaluation.feedbackSections)
        {
            if (section == null)
                continue;
            if (!string.IsNullOrWhiteSpace(section.body) ||
                !string.IsNullOrWhiteSpace(section.title) ||
                !string.IsNullOrWhiteSpace(section.sectionId))
            {
                return true;
            }
        }

        return false;
    }

    public string FormatSharedNarrativeReport(DynamicEvaluationResult evaluation, int conversationCount)
    {
        StringBuilder report = new StringBuilder();
        report.Append(CreateNarrativeHeader(evaluation));
        report.AppendLine();
        report.Append(CreateNarrativeSummary(evaluation, conversationCount));
        report.AppendLine();
        report.Append(CreateNarrativeSections(evaluation));
        report.AppendLine();
        report.Append(CreateNarrativeFooter());
        return report.ToString();
    }

    private string CreateNarrativeHeader(DynamicEvaluationResult evaluation)
    {
        StringBuilder header = new StringBuilder();
        header.AppendLine($"<size={headerSize}><color=#{ColorUtility.ToHtmlStringRGB(headerColor)}><b>AI INTERACTION FEEDBACK REPORT</b></color></size>");
        header.AppendLine($"<color=#{ColorUtility.ToHtmlStringRGB(subHeaderColor)}>{DeriveSubtitle(evaluation?.feedbackUse)}</color>");
        header.AppendLine("=================================================");
        header.AppendLine();
        header.AppendLine($"<b>Date:</b> {System.DateTime.Now:MMMM dd, yyyy}");
        header.AppendLine($"<b>Time:</b> {System.DateTime.Now:HH:mm}");
        header.AppendLine($"<b>Feedback Type:</b> {DeriveSubtitle(evaluation?.feedbackUse)}");
        header.AppendLine($"<b>Generated By:</b> {DeriveSource(evaluation?.feedbackSource)}");
        return header.ToString();
    }

    private string CreateNarrativeSummary(DynamicEvaluationResult evaluation, int conversationCount)
    {
        StringBuilder summary = new StringBuilder();
        summary.AppendLine($"<size={subHeaderSize}><color=#{ColorUtility.ToHtmlStringRGB(subHeaderColor)}><b>INTERACTION SUMMARY</b></color></size>");
        summary.AppendLine("=========================================");
        summary.AppendLine();
        if (conversationCount > 0)
            summary.AppendLine($"• <b>Total Dialogue Exchanges:</b> {conversationCount}");
        summary.AppendLine("• <b>Review Basis:</b> Student-patient interaction and task evidence");
        summary.AppendLine($"• <b>Task Focus:</b> {DeriveTaskFocus(evaluation)}");

        string overall = evaluation?.overallExplanation;
        if (!string.IsNullOrWhiteSpace(overall))
        {
            summary.AppendLine();
            summary.AppendLine(EscapeRichText(overall.Trim()));
        }

        return summary.ToString();
    }

    private string CreateNarrativeSections(DynamicEvaluationResult evaluation)
    {
        StringBuilder body = new StringBuilder();
        if (evaluation == null || evaluation.feedbackSections == null || evaluation.feedbackSections.Count == 0)
        {
            body.AppendLine("<i>No feedback sections were provided.</i>");
            return body.ToString();
        }

        List<NarrativeFeedbackSection> ordered = NormalizeSectionOrder(evaluation.feedbackSections);
        bool wroteAny = false;
        foreach (NarrativeFeedbackSection section in ordered)
        {
            if (section == null)
                continue;
            string sectionBody = section.body;
            if (string.IsNullOrWhiteSpace(sectionBody))
                continue;

            string title = !string.IsNullOrWhiteSpace(section.title)
                ? section.title.Trim()
                : HumanizeSectionId(section.sectionId);

            body.AppendLine($"<size={subHeaderSize}><color=#{ColorUtility.ToHtmlStringRGB(subHeaderColor)}><b>{EscapeRichText(title.ToUpper())}</b></color></size>");
            body.AppendLine("=========================================");
            body.AppendLine();
            body.AppendLine(EscapeRichText(sectionBody.Trim()));
            body.AppendLine();
            wroteAny = true;
        }

        if (!wroteAny)
            body.AppendLine("<i>No feedback content was provided.</i>");

        return body.ToString();
    }

    private string CreateNarrativeFooter()
    {
        StringBuilder footer = new StringBuilder();
        footer.AppendLine("=========================================");
        footer.AppendLine($"<i>Report generated on {System.DateTime.Now:MMMM dd, yyyy} at {System.DateTime.Now:HH:mm}</i>");
        footer.AppendLine("<i>For questions about this feedback, consult with your clinical instructor.</i>");
        return footer.ToString();
    }

    private static string DeriveSubtitle(string feedbackUse)
    {
        if (string.IsNullOrWhiteSpace(feedbackUse))
            return "AI Interaction Feedback";
        switch (feedbackUse.Trim().ToLowerInvariant())
        {
            case "phase1_ai_interaction": return "Phase 1 AI Interaction Feedback";
            case "phase2_training":       return "Phase 2 Training Feedback";
            case "phase3_debrief":        return "Debrief Feedback";
            default:                      return "AI Interaction Feedback";
        }
    }

    private static string DeriveSource(string feedbackSource)
    {
        if (string.IsNullOrWhiteSpace(feedbackSource))
            return "AI Feedback System";
        switch (feedbackSource.Trim().ToLowerInvariant())
        {
            case "ai":      return "AI Feedback System";
            case "faculty": return "Faculty Expert";
            default:        return feedbackSource.Trim();
        }
    }

    private static string DeriveTaskFocus(DynamicEvaluationResult evaluation)
    {
        string taskType = evaluation?.metadata?.taskType;
        if (string.IsNullOrWhiteSpace(taskType))
            return "Interaction quality and supportive communication";
        switch (taskType.Trim().ToLowerInvariant())
        {
            case "object_naming_with_cueing":
                return "Cueing strategy and adaptation";
            case "sentence_completion_practice":
                return "Prompting and sentence-stem quality";
            default:
                return "Interaction quality and supportive communication";
        }
    }

    private static List<NarrativeFeedbackSection> NormalizeSectionOrder(List<NarrativeFeedbackSection> sections)
    {
        List<NarrativeFeedbackSection> ordered = new List<NarrativeFeedbackSection>(sections.Count);
        HashSet<int> claimedIndices = new HashSet<int>();

        foreach (string canonicalId in CanonicalSectionOrder)
        {
            for (int i = 0; i < sections.Count; i++)
            {
                if (claimedIndices.Contains(i))
                    continue;
                NarrativeFeedbackSection candidate = sections[i];
                if (candidate == null || string.IsNullOrWhiteSpace(candidate.sectionId))
                    continue;
                if (string.Equals(candidate.sectionId.Trim(), canonicalId, System.StringComparison.OrdinalIgnoreCase))
                {
                    ordered.Add(candidate);
                    claimedIndices.Add(i);
                    break;
                }
            }
        }

        for (int i = 0; i < sections.Count; i++)
        {
            if (claimedIndices.Contains(i))
                continue;
            NarrativeFeedbackSection leftover = sections[i];
            if (leftover == null)
                continue;
            ordered.Add(leftover);
        }

        return ordered;
    }

    private static string HumanizeSectionId(string sectionId)
    {
        if (string.IsNullOrWhiteSpace(sectionId))
            return "Feedback";
        string normalized = sectionId.Trim().Replace('_', ' ').Replace('-', ' ');
        StringBuilder builder = new StringBuilder(normalized.Length);
        bool nextUpper = true;
        foreach (char c in normalized)
        {
            if (char.IsWhiteSpace(c))
            {
                builder.Append(c);
                nextUpper = true;
                continue;
            }
            builder.Append(nextUpper ? char.ToUpperInvariant(c) : c);
            nextUpper = false;
        }
        return builder.ToString();
    }

    private static string EscapeRichText(string value)
    {
        if (string.IsNullOrEmpty(value))
            return value;
        return value.Replace("<", "&lt;").Replace(">", "&gt;");
    }

    // =====================================================================
    // Editor-only preview entry points (visible only in the Inspector).
    // =====================================================================

    [ContextMenu("Preview / Phase 1 AI Interaction Feedback")]
    private void DEBUG_PreviewPhase1Narrative()
    {
        ApplyFormattedReport(BuildSamplePhase1Narrative(), conversationCount: 12);
    }

    [ContextMenu("Preview / Phase 2 Training Feedback")]
    private void DEBUG_PreviewPhase2Narrative()
    {
        ApplyFormattedReport(BuildSamplePhase2Narrative(), conversationCount: 0);
    }

    [ContextMenu("Preview / Phase 3 Faculty Feedback")]
    private void DEBUG_PreviewPhase3FacultyNarrative()
    {
        ApplyFormattedReport(BuildSamplePhase3FacultyNarrative(), conversationCount: 0);
    }

    private static DynamicEvaluationResult BuildSamplePhase1Narrative()
    {
        return new DynamicEvaluationResult
        {
            feedbackUse = "phase1_ai_interaction",
            feedbackSource = "ai",
            overallExplanation = "The student maintained a calm, supportive tone throughout the interaction and elicited several relevant responses. Scoring decisions showed a tendency to credit partial responses as fully correct on items where the rubric distinguishes partial from complete.",
            metadata = new FeedbackReportMetadata
            {
                phaseId = "phase1",
                taskType = "supported_conversation_techniques",
                patientProfile = "preview"
            },
            feedbackSections = new List<NarrativeFeedbackSection>
            {
                new NarrativeFeedbackSection { sectionId = "interaction_overview", title = "Interaction Overview", body = "The session moved at a comfortable pace, with the student introducing themselves, explaining the session purpose, and giving the patient time to respond. Probing follow-ups were used selectively rather than systematically." },
                new NarrativeFeedbackSection { sectionId = "rapport_communication", title = "Rapport and Communication", body = "Warm greeting and active listening were evident. The student used short, simple sentences during difficult moments — a strong supportive-communication choice." },
                new NarrativeFeedbackSection { sectionId = "clinical_reasoning", title = "Clinical Reasoning", body = "Information was gathered in a generally systematic order, but follow-up questioning on items with ambiguous patient responses was inconsistent." },
                new NarrativeFeedbackSection { sectionId = "assessment_judgment", title = "Assessment Judgment", body = "Scoring decisions matched the rubric on items with clear-cut responses. Mismatches clustered on items requiring the student to distinguish partial from complete responses, where the student tended to assign higher scores than the rubric expected." },
                new NarrativeFeedbackSection { sectionId = "priority_improvements", title = "Priority Improvement Areas", body = "Practice distinguishing partial-credit responses from fully-correct responses, particularly on items where the patient produced a related but non-target word. Review the rubric criteria for partial credit before the next assessment session." },
                new NarrativeFeedbackSection { sectionId = "next_step_practice", title = "Next-Step Practice Suggestions", body = "Replay the recorded session and pause after each patient response to score independently before checking the rubric guidance. Discuss two or three discrepant items with a clinical instructor." }
            }
        };
    }

    private static DynamicEvaluationResult BuildSamplePhase2Narrative()
    {
        return new DynamicEvaluationResult
        {
            feedbackUse = "phase2_training",
            feedbackSource = "ai",
            overallExplanation = "Across the practice items the student used cueing prompts with growing confidence, advancing to phonemic cues when semantic cues did not elicit the target.",
            metadata = new FeedbackReportMetadata
            {
                phaseId = "phase2",
                taskType = "object_naming_with_cueing",
                patientProfile = "ben"
            },
            feedbackSections = new List<NarrativeFeedbackSection>
            {
                new NarrativeFeedbackSection { sectionId = "cueing_strategy", title = "Cueing Strategy", body = "Semantic cues were tried first on most items, with phonemic cues introduced after the first unsuccessful attempt. Consider waiting an additional moment before escalating, since several targets were named immediately after a brief pause." },
                new NarrativeFeedbackSection { sectionId = "adaptation_to_patient", title = "Adaptation to Patient Difficulty", body = "On items where the patient produced a partial response, the student stayed on the same cue level rather than escalating prematurely — an effective adaptation." },
                new NarrativeFeedbackSection { sectionId = "strengths", title = "Key Strengths", body = "Consistent supportive tone, accurate identification of when to advance to the next target, and clear awareness of cue hierarchy." },
                new NarrativeFeedbackSection { sectionId = "priority_improvements", title = "Priority Improvement Areas", body = "Allow longer post-cue wait time before re-cueing. Practice varying semantic cue phrasing when a first semantic attempt does not elicit the target." },
                new NarrativeFeedbackSection { sectionId = "next_step_practice", title = "Next-Step Practice Suggestions", body = "Run another Object Naming block focused on the four targets that required model-level cueing in this session." }
            }
        };
    }

    private static DynamicEvaluationResult BuildSamplePhase3FacultyNarrative()
    {
        return new DynamicEvaluationResult
        {
            feedbackUse = "phase3_debrief",
            feedbackSource = "faculty",
            overallExplanation = "Faculty review of the session highlighted strong supportive-communication choices and a developing sense of when to escalate cueing.",
            metadata = new FeedbackReportMetadata
            {
                phaseId = "phase2",
                taskType = "sentence_completion_practice",
                patientProfile = "maria",
                facultyId = "preview-faculty-A"
            },
            feedbackSections = new List<NarrativeFeedbackSection>
            {
                new NarrativeFeedbackSection { sectionId = "prompting_quality", title = "Prompting Quality", body = "Sentence stems were generally well-formed; consider making the missing target word position more salient on stems where the patient produced a related-but-different completion." },
                new NarrativeFeedbackSection { sectionId = "adaptation_to_patient", title = "Adaptation to Patient Difficulty", body = "Maria's slower response pacing was respected throughout. The student used short, clear stems and avoided rephrasing mid-utterance." },
                new NarrativeFeedbackSection { sectionId = "strengths", title = "Key Strengths", body = "Warm tone, patient pacing, and thoughtful use of phonemic cues when semantic prompts plateaued." },
                new NarrativeFeedbackSection { sectionId = "next_step_practice", title = "Next-Step Practice Suggestions", body = "Try a sentence-completion block where the missing word falls in different positions (initial, medial, final) to give the student practice varying stem construction." }
            }
        };
    }

    // 可选：保存报告为文本文件
    public void SaveReportToFile(DynamicEvaluationResult evaluation, int conversationCount)
    {
        string content = FormatMedicalReport(evaluation, conversationCount);
        string fileName = $"NursingAssessment_{System.DateTime.Now:yyyyMMdd_HHmmss}.txt";
        string path = System.IO.Path.Combine(Application.persistentDataPath, fileName);

        System.IO.File.WriteAllText(path, content);
        Debug.Log($"Report saved to: {path}");
    }
}
